web:
  port: 8000
  public_url: "http://localhost:8000"

database:
  url: "postgresql://citta@localhost:5432/citta"

google:
  oauth_client_id: "879655223584-mki9ft91b9s8jrrorng1ptlal87ea846.apps.googleusercontent.com"
  oauth_client_secret: "UJdPOQwTUnlOTolciem-1ThE"

quickbooks:
  base_url: "https://sandbox-quickbooks.api.intuit.com"
  client_id: "AB1rRLhRyyo2xExzSAfDXBTShzUTckQlzHYLCRXvOOpoyNUPW4"
  client_secret: "5eDIVIgzbWwZ7B3LHIio3D4wXUPfpjzpTYa2R1bp"
  scope: "com.intuit.quickbooks.accounting"
  redirect_uri: "http://localhost:8000/oauth/quickbooks/callback"
  discovery_doc: "https://developer.api.intuit.com/.well-known/openid_sandbox_configuration"

slack:
  host: "slack.com"
  app_token: ""
  oauth2_client_id: ""
  oauth2_client_secret: ""
  authorization_endpoint: "https://slack.com/oauth/v2/authorize"
  token_endpoint: "https://slack.com/api/oauth.v2.access"
  redirect_uri: "https://localhost:8001/oauth/slack/callback"
  slash_command_name: "citta"
  slash_command_token: ""
  incoming_webhook_url: ""
  admin_username: ""
  admin_id: ""
  team_id: ""
  info_op_channel_id: ""
  info_op_channel_name: ""
  support_channel_id: ""
  support_channel_name: ""
  admin_channel_id: ""
  admin_channel_name: ""

brium:
  origin: "https://brium.me"
  oauth2_client_id: "9324e49b3a8e13654d537629c7dc6cb365cdcee0a05bd9a1b5067ad2fbfc600a"
  oauth2_client_secret: "e5d8fb057a2d5afde6c673ee7cb702e4835afa2ed0df25ffd06d75506f77d63d"
  authorization_endpoint: "https://brium.me/oauth2/authorize"
  token_endpoint: "https://brium.me/oauth2/token"
  redirect_uri: "http://localhost:8000/oauth/brium/callback"

currency_layer:
  api_key: ""

api_layer:
  api_key: "XXXX"

stripe:
  api_key: "sk_test_51J06TAAxmG8F6OKsWVRvIugjQKAfBMa690mCqY7LF8XXH4rMiXSB8fufUKUjVPSrfkDnnuedwCM6RhAZnFiM4XdY00RyEsi1pn"
